cluster.name: "elasticsearch-docker-cluster"
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node
xpack.security.enabled: false
bootstrap.memory_lock: false
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
